name: Build Flatpak CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
      options: "--privileged --cap-add SYS_ADMIN --device /dev/fuse"
    steps:
      - name: "Code Checkout"
        uses: actions/checkout@v5

      - name: "Install BuildStream2"
        run: |
          sudo dnf group install -y c-development
          sudo dnf install -y flatpak bubblewrap fuse3 git lzip patch python3-devel python3-pip fuse3 fuse3-devel node
          pip install buildstream buildstream-plugins buildstream-external bst-plugins-experimental dulwich==0.24.10

      - name: "Build .bst file"
        run: bst build rocm-flatpak.bst

      - name: "Bst Artifact"
        run: bst artifact checkout --directory ./rocm-repo rocm-flatpak.bst

      - name: "Add Flatpak Remote"
        run: flatpak remote-add --user rocm-repo ./rocm-repo --no-gpg-verify

      - name: "Install Flatpak"
        run: flatpak install -y --user org.freedesktop.Platform.GL.ROCm

      - name: "Build Flatpak"
        run: flatpak build-bundle --runtime ./rocm-repo rocm.flatpak org.freedesktop.Platform.GL.ROCm 25.08

      - name: "Release to Github"
        uses: ncipollo/release-action@v1
        with:
          artifacts: "rocm.flatpak"
          tag: "latest"
          commit: ${{ github.sha }}
          allowUpdates: true
